### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by dreispt** [OCA/product-configurator#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [x] <s>product_configurator  => @Chandresh-OSI #1</s>
- [x] <s>product_configurator_mrp => @Chandresh-OSI #6</s>
- [x] <s>product_configurator_purchase</s>
- [x] <s>product_configurator_sale @Chandresh-OSI  #3</s>
- [x] <s>product_configurator_sale_mrp @Chandresh-OSI #7 </s>
- [x] <s>product_configurator_stock</s>
- [ ] product_configurator_stock_lots
- [ ] product_configurator_subconfig
- [x] <s>website_product_configurator @bizzappdev #12</s>
- [x] <s>website_product_configurator_mrp @pledrateam #26</s>

**Comment by dreispt** [comment]
cc @Chandresh-osi

**Comment by PCatinean** [comment]
@dreispt we had previous migration work with multiple other fixes included. We did not know if we could pick them up due to high workload but now we had a chance to get back to it. I think our current PR superseeds the existing one. Can we change assignment to https://github.com/pledrateam ?

For the record tha plan is to have a PR with migration of the current state and then start refactoring different sections for which I have created issues.

**Comment by dreispt** [comment]
@PCatinean It would have been nice to have shared existing work when we mentioned we wanted to work on the v14 migration. 
We have been working on this for two weeks, and I understand we are to throw away all this work.

I'm happy to let you lead on this.
Just let me know exactly what you want to do next.
You might want to consider reusing and building on top or our PR #1.

Thanks

**Comment by PCatinean** [comment]
As said we had previous effort that was stopped even before we took the decision to move to OCA but ok we will try to rebase on the existing PR.

**Comment by dreispt** [comment]
OK, we are stopping all work and waiting for your PRs.

**Comment by dreispt** [comment]
@PCatinean I see no PR form you, so I believe you're yet to start work.
I have delivery dates to meet, so I must move on.
I'm sure fixes and refactoring will be needed, but #1 is now has a green build, so I moved on and merged it.

@Chandresh-OSI Please proceed with work on #3

**Comment by PCatinean** [comment]
I am not sure why you would assume I have not even started anything Daniel when I mentioned we already have work pending. I have not opened until now because of some delays and my vacation started as well. Regardless you can go ahead and do your thing no problem.

**Comment by dreispt** [comment]
@PCatinean Show me the code. I don't see any PRs here.

By the way, there was non trivial work done to get a TravisCI build, including breaking big methods into smaller ones, to get through the "too complex" check fails. So I think it will save you dozens of hours starting the existing migration code.

Can you please open your WIP PRs so we can collaborate and know what each is working on?

**Comment by bizzappdev** [comment]
website_product_configurator #12

**Comment by bizzappdev** [comment]
website_product_configurator  #12 @pledrateam  is working on it

**Comment by pledrateam** [comment]
product_configurator_stock #29

**Comment by pledrateam** [comment]
product_configurator_purchase #31

**Comment by pledrateam** [comment]
website_product_configurator_mrp #32
